name: "Publish to GitHub Pages"

env:
  GODOT_VERSION: 4.3

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Create Export Directory
        run: mkdir -p export

      - name: Export Game
        run: |
          godot --headless --export-release "MonkeGame" "export/MonkeGame.html"
        env:
          GODOT_VERBOSE: "1"

      - name: Add COI Service Worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js export/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' export/MonkeGame.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./export
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages"
